In [7]:
# import all packages needed
import pandas as pd
import numpy as np
from sklearn import linear_model

In [9]:
cd /home/greg/Master\ Courses/

/home/greg/Master Courses


In [10]:
cd Machine_Learning/1_Regularization_Sparsity/Exercise/

/home/greg/Master Courses/Machine_Learning/1_Regularization_Sparsity/Exercise


In [12]:
# Importing the data and creating the labels for the two classes (-1 zeros, 1 ones)
# 554 zero images and 571 one images
data = pd.read_csv('dataset.csv',header=0,index_col=False)
labs = 554*[-1] + 571*[1]
labels = pd.Series(labs)
data = data.drop('Unnamed: 0',1)

In [21]:
# Creating a matrix of the data and a list of the labels
dataAsMat = data.as_matrix
dataMat = dataAsMat()
labelsList = list(labels)

# testing the values of the matrix below
dataMat

array([[  0,  16,  96, ...,  16,   0,   0],
       [  0,   0, 160, ...,  48,   0,   0],
       [  0,   0, 240, ...,   0,   0,   0],
       ..., 
       [  0,   0,  16, ..., 160,   0,   0],
       [  0,   0, 128, ..., 112,   0,   0],
       [  0,   0,  96, ...,  64,   0,   0]])

In [22]:
# testing the values of the labels list below
labelsList

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,


In [37]:
# fit a model to the data with λ = 10^(-3) ... 10^3
clf = linear_model.Ridge(alpha=0.001)
clf.fit(dataMat,labelsList)
w0001=np.around(clf.coef_,decimals=4)

clf = linear_model.Ridge(alpha=0.01)
clf.fit(dataMat,labelsList)
w001=np.around(clf.coef_,decimals=4)

clf = linear_model.Ridge(alpha=0.1)
clf.fit(dataMat,labelsList)
w01=np.around(clf.coef_,decimals=4)

clf = linear_model.Ridge(alpha=1)
clf.fit(dataMat,labelsList)
w1=np.around(clf.coef_,decimals=4)

clf = linear_model.Ridge(alpha=10)
clf.fit(dataMat,labelsList)
w10=np.around(clf.coef_,decimals=4)

clf = linear_model.Ridge(alpha=100)
clf.fit(dataMat,labelsList)
w100=np.around(clf.coef_,decimals=4)

clf = linear_model.Ridge(alpha=1000)
clf.fit(dataMat,labelsList)
w1000=np.around(clf.coef_,decimals=4)

for w in [w0001,w001,w01,w1,w10,w100,w1000]:
    print(w)

[ 0.      0.      0.0001  0.0002 -0.0001  0.0005  0.0022  0.      0.      0.
 -0.0003 -0.0002  0.0004  0.     -0.      0.     -0.0028  0.0007  0.0002
  0.0005  0.0005 -0.0006  0.      0.      0.013  -0.0002 -0.0001  0.0006
  0.0023 -0.0002 -0.0005  0.      0.     -0.0002 -0.0002  0.0006  0.0013
  0.0002 -0.0014  0.      0.     -0.0003 -0.0007  0.001  -0.0001 -0.0003
 -0.0002  0.      0.     -0.0001 -0.0003 -0.0003 -0.0008 -0.0003 -0.
  0.0007  0.     -0.0055  0.0012 -0.0009 -0.0005  0.0003  0.0011  0.0002]
[ 0.      0.      0.0001  0.0002 -0.0001  0.0005  0.0022  0.      0.      0.
 -0.0003 -0.0002  0.0004  0.     -0.      0.     -0.0028  0.0007  0.0002
  0.0005  0.0005 -0.0006  0.      0.      0.013  -0.0002 -0.0001  0.0006
  0.0023 -0.0002 -0.0005  0.      0.     -0.0002 -0.0002  0.0006  0.0013
  0.0002 -0.0014  0.      0.     -0.0003 -0.0007  0.001  -0.0001 -0.0003
 -0.0002  0.      0.     -0.0001 -0.0003 -0.0003 -0.0008 -0.0003 -0.
  0.0007  0.     -0.0055  0.0012 -0.0009 -0.0005  

In [27]:
import Image

ImportError: No module named Image

In [28]:
from PIL import Image
dataMatrix.min()

0

In [29]:
dataMatrix.shape

(1125, 64)

In [36]:
w0_1Image = (((w0_1- w0_1.min()) / (w0_1.max() - w0_1.min())) * 255.9).astype(np.uint8)

In [39]:
w0_1Image.shape

(64,)

In [38]:
img = Image.fromarray(w0_1Image)

IndexError: tuple index out of range

In [33]:
img.save('w0_1.png')

In [35]:
w0_1

array([ 0.    ,  0.    ,  0.0001,  0.0002, -0.0001,  0.0005,  0.0022,
        0.    ,  0.    ,  0.    , -0.0003, -0.0002,  0.0004,  0.    ,
       -0.    ,  0.    , -0.0028,  0.0007,  0.0002,  0.0005,  0.0005,
       -0.0006,  0.    ,  0.    ,  0.013 , -0.0002, -0.0001,  0.0006,
        0.0023, -0.0002, -0.0005,  0.    ,  0.    , -0.0002, -0.0002,
        0.0006,  0.0013,  0.0002, -0.0014,  0.    ,  0.    , -0.0003,
       -0.0007,  0.001 , -0.0001, -0.0003, -0.0002,  0.    ,  0.    ,
       -0.0001, -0.0003, -0.0003, -0.0008, -0.0003, -0.    ,  0.0007,
        0.    , -0.0055,  0.0012, -0.0009, -0.0005,  0.0003,  0.0011,
        0.0002])

In [40]:
w0_1.shape


(64,)

In [41]:
w0_1

array([ 0.    ,  0.    ,  0.0001,  0.0002, -0.0001,  0.0005,  0.0022,
        0.    ,  0.    ,  0.    , -0.0003, -0.0002,  0.0004,  0.    ,
       -0.    ,  0.    , -0.0028,  0.0007,  0.0002,  0.0005,  0.0005,
       -0.0006,  0.    ,  0.    ,  0.013 , -0.0002, -0.0001,  0.0006,
        0.0023, -0.0002, -0.0005,  0.    ,  0.    , -0.0002, -0.0002,
        0.0006,  0.0013,  0.0002, -0.0014,  0.    ,  0.    , -0.0003,
       -0.0007,  0.001 , -0.0001, -0.0003, -0.0002,  0.    ,  0.    ,
       -0.0001, -0.0003, -0.0003, -0.0008, -0.0003, -0.    ,  0.0007,
        0.    , -0.0055,  0.0012, -0.0009, -0.0005,  0.0003,  0.0011,
        0.0002])

In [42]:
w0_1Image = np.ndarray(shape=(8,8
                             ))

In [43]:
w0_1Image

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [44]:
lims = [8,16,24,32,40,48,56,64]

In [48]:
for i in range(0,8):
    w0_1Image[i,:] = w0_1[i*8:lims[i]]

In [49]:
w0_1Image

array([[ 0.    ,  0.    ,  0.0001,  0.0002, -0.0001,  0.0005,  0.0022,  0.    ],
       [ 0.    ,  0.    , -0.0003, -0.0002,  0.0004,  0.    , -0.    ,  0.    ],
       [-0.0028,  0.0007,  0.0002,  0.0005,  0.0005, -0.0006,  0.    ,  0.    ],
       [ 0.013 , -0.0002, -0.0001,  0.0006,  0.0023, -0.0002, -0.0005,  0.    ],
       [ 0.    , -0.0002, -0.0002,  0.0006,  0.0013,  0.0002, -0.0014,  0.    ],
       [ 0.    , -0.0003, -0.0007,  0.001 , -0.0001, -0.0003, -0.0002,  0.    ],
       [ 0.    , -0.0001, -0.0003, -0.0003, -0.0008, -0.0003, -0.    ,
         0.0007],
       [ 0.    , -0.0055,  0.0012, -0.0009, -0.0005,  0.0003,  0.0011,
         0.0002]])

In [50]:
w01Image = (((w0_1Image- w0_1Image.min()) / (w0_1Image.max() - w0_1Image.min())) * 255.9).astype(np.uint8)

In [51]:
w01Image

array([[ 76,  76,  77,  78,  74,  82, 106,  76],
       [ 76,  76,  71,  73,  81,  76,  76,  76],
       [ 37,  85,  78,  82,  82,  67,  76,  76],
       [255,  73,  74,  84, 107,  73,  69,  76],
       [ 76,  73,  73,  84,  94,  78,  56,  76],
       [ 76,  71,  66,  89,  74,  71,  73,  76],
       [ 76,  74,  71,  71,  65,  71,  76,  85],
       [ 76,   0,  92,  63,  69,  80,  91,  78]], dtype=uint8)

In [52]:
w0_1Image.max()

0.012999999999999999

In [53]:
img = Image.fromarray(w01Image)

In [54]:
img.save('w01.png')

In [57]:
clf = linear_model.Ridge(alpha=10000000)
clf.fit(dataMatrix,labelsList)
np.around(clf.coef_,decimals=4)

array([ 0.    , -0.    ,  0.    , -0.0002, -0.0001,  0.0004,  0.0001,
        0.    ,  0.    , -0.    , -0.0003, -0.0001,  0.0001, -0.0001,
        0.0001,  0.    ,  0.    ,  0.    , -0.0002,  0.0006,  0.0008,
       -0.0004, -0.0001,  0.    ,  0.    , -0.0001, -0.0002,  0.0008,
        0.001 , -0.0001, -0.0004,  0.    ,  0.    , -0.0003, -0.0004,
        0.0007,  0.001 , -0.0001, -0.0005,  0.    ,  0.    , -0.0002,
       -0.0006,  0.0005,  0.0007, -0.0003, -0.0004,  0.    ,  0.    ,
       -0.    , -0.0004, -0.0001, -0.    , -0.0003,  0.0001,  0.    ,
        0.    ,  0.    ,  0.    , -0.0003, -0.0002,  0.0004,  0.0003,
        0.0001])

In [58]:
def RidgeGradientDescent(x, y, alpha, iters, L):
    x=np.matrix(x)
    y=np.matrix(y).transpose()
    m, n = np.shape(x)
    beta = np.matrix(np.ones(n)).transpose()
    XT = x.transpose()
    for i in range(0, iters):
        y_hat = np.dot(x, beta)
        residuals = y_hat - y
        MSE = (residuals.transpose()*residuals)/len(x)
        print "iteration:", i, "MSE:", MSE
        ols_gradient = np.dot(XT, residuals) / m
        beta = beta - alpha * (ols_gradient + (L/m)*beta)
    return beta


In [66]:
RidgeGradientDescent(dataMatrix,labelsList,.1,10,0.1)

iteration: 0 MSE: [[ 26785681.82044445]]
iteration: 1 MSE: [[  1.54452569e+17]]
iteration: 2 MSE: [[  8.92500139e+26]]
iteration: 3 MSE: [[  5.15731696e+36]]
iteration: 4 MSE: [[  2.98015879e+46]]
iteration: 5 MSE: [[  1.72208660e+56]]
iteration: 6 MSE: [[  9.95108804e+65]]
iteration: 7 MSE: [[  5.75024238e+75]]
iteration: 8 MSE: [[  3.32278111e+85]]
iteration: 9 MSE: [[  1.92007112e+95]]


matrix([[  9.99911115e-01],
        [  1.46450824e+46],
        [  2.40917760e+48],
        [  7.79243709e+48],
        [  7.70558171e+48],
        [  3.01380812e+48],
        [  2.51542266e+47],
        [  9.99911115e-01],
        [  9.99911115e-01],
        [  4.37491962e+47],
        [  6.08688563e+48],
        [  9.13367179e+48],
        [  9.38714392e+48],
        [  6.98313104e+48],
        [  6.25754987e+47],
        [  9.99911115e-01],
        [  8.76781550e+45],
        [  1.75667589e+48],
        [  7.72080353e+48],
        [  7.02891669e+48],
        [  6.24500452e+48],
        [  7.19649817e+48],
        [  1.35784315e+48],
        [  9.99911115e-01],
        [  2.83204934e+45],
        [  2.58959851e+48],
        [  7.90599666e+48],
        [  5.87320832e+48],
        [  5.29591495e+48],
        [  5.76361716e+48],
        [  2.37568291e+48],
        [  9.99911115e-01],
        [  9.99911115e-01],
        [  2.40122283e+48],
        [  6.74673133e+48],
        [  4.7399756

In [61]:
from scipy import stats
z = stats.zscore(dataMatrix,axis=0)
Y= stats.zscore(labelsList)

In [68]:
dataMatrix.shape

(1125, 64)

In [69]:
dataMatrix[0:1,:]

array([[  0,  16,  96, 240, 192,  16,   0,   0,   0, 112, 255,  96,  96,
        160,   0,   0,   0, 128, 255,  32,   0, 176,  32,   0,   0,  80,
        255,  48,   0,  80, 112,   0,   0, 112, 208,  48,   0, 128, 112,
          0,   0,  64, 192,   0,  16, 208,  80,   0,   0,   0, 224, 144,
        240, 144,   0,   0,   0,   0,  96, 224, 112,  16,   0,   0]])

In [72]:
eqdataMatrix = dataMatrix[0:1108,:]

In [73]:
eqdataMatrix.shape


(1108, 64)

In [74]:
labelsList

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,


In [76]:
eqlabelsList = labelsList[0:1108]

In [77]:
print eqlabelsList.count(-1)
print eqlabelsList.count(1)

554
554


In [86]:
clf = linear_model.RidgeClassifier(alpha=100000000000000)
clf.fit(eqdataMatrix,eqlabelsList)
np.around(clf.coef_,decimals=4)

array([[ 0., -0., -0., -0., -0.,  0.,  0.,  0.,  0., -0., -0., -0.,  0.,
        -0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,  0., -0.,
        -0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,
         0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,
         0., -0., -0.,  0.,  0.,  0., -0., -0., -0.,  0.,  0.,  0.]])

In [83]:
zerosMean = np.mean(eqdataMatrix[0:554],axis=0)
onesMean = np.mean(eqdataMatrix[554:],axis=0)
difMean = zerosMean - onesMean

In [87]:
zerosMean

array([   0.        ,    0.433213  ,   70.95848375,  210.26895307,
        176.84476534,   43.66606498,    0.80866426,    0.        ,
          0.        ,   17.24187726,  205.30505415,  210.69855596,
        192.16064982,  174.79241877,   12.99638989,    0.        ,
          0.        ,   61.25631769,  228.99638989,   77.97292419,
         43.33393502,  200.64259928,   54.23826715,    0.        ,
          0.        ,   83.98555957,  203.58303249,   28.33032491,
          4.30144404,  146.61371841,  105.15523466,    0.        ,
          0.        ,   89.09747292,  188.53249097,   14.84476534,
          2.19314079,  139.23465704,  116.85198556,    0.        ,
          0.        ,   53.97833935,  214.95848375,   27.97833935,
         23.67689531,  181.63898917,  100.18411552,    0.        ,
          0.        ,   12.3898917 ,  209.40433213,  165.88628159,
        168.5631769 ,  214.33032491,   41.6732852 ,    0.        ,
          0.        ,    0.23104693,   70.96028881,  216.69494